/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: operations['AuthController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login a user */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload a file */
    post: operations['FilesController_upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/download/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get file metadata by download token */
    get: operations['FilesController_getInfo'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/download/{token}/content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download file by token */
    get: operations['FilesController_download'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateUserDto: {
      /** @example user@example.com */
      email: string;
      password: string;
    };
    LoginUserDto: {
      /** @example user@example.com */
      email: string;
      password: string;
    };
    FileEntity: {
      id: string;
      originalName: string;
      mimeType: string;
      size: number;
      downloadToken: string;
      /** Format: date-time */
      createdAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserDto'];
      };
    };
    responses: {
      /** @description Account created (or silently ignored if email exists) */
      201: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Validation error */
      400: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginUserDto'];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description Invalid credentials */
      401: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  FilesController_upload: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description File uploaded successfully */
      201: {
        headers: Record<string, unknown>;
        content: {
          'application/json': components['schemas']['FileEntity'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description File exceeds the size limit */
      413: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description File type not allowed */
      415: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  FilesController_getInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File metadata */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description File not found */
      404: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
  FilesController_download: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description File stream */
      200: {
        headers: Record<string, unknown>;
        content?: never;
      };
      /** @description File not found */
      404: {
        headers: Record<string, unknown>;
        content?: never;
      };
    };
  };
}
